remote_theme: brentyi/osa

title: The Blue Gripper
description: This website is for the paper "Blue Gripper: A Robust, Low-Cost, and Force-Controlled Robot Hand"

matomo_url: brentyi.com/piwik
matomo_site_id: 3

collections:
  sections:
    output: false

sass:
  style: compressed


theme: jekyll-theme-slate
