remote_theme: brentyi/osa

title: Robust and Low-Cost Gripper Design for Robotic Manipulation in Unstructured Environments

matomo_url: brentyi.com/piwik
matomo_site_id: 3

collections:
  sections:
    output: false

sass:
  style: compressed


theme: jekyll-theme-slate
